"""Raise an invoice for every subscription whose period has started.

One row per subscription per period, generated by the platform jobs process
and never by a request - a tenant does not ask to be invoiced, and an operator
does not click a button per customer.

Everything on the invoice is SNAPSHOTTED at issue: the plan's name and price,
the coupon's code and percentage, the GST rate, the SAC code, both parties'
GSTINs and state codes. The plan can be renamed, the coupon deactivated, the
rate changed by the Finance Ministry - the invoice still says what was
invoiced. An invoice that reads through to live rows is a document that
rewrites itself.

GST, decided once and written down:

  * The seller is in the state SELLER_STATE_CODE names. If the buyer's
    ``core.organisations.state_code`` is the same, the supply is intra-state and
    the tax is CGST + SGST, each half the rate. Otherwise it is IGST at the
    full rate. That is the whole rule for a B2B service, and the split is a
    column on the row so an accountant can read it without re-deriving it.

  * No buyer state on file is not "assume intra-state". It is an invoice that
    cannot be issued, recorded as a DRAFT with no number, and a line in the job
    detail naming the organisation - because the alternative is a GST document
    with the wrong tax on it.

The number is taken from a sequence at ISSUE, not at draft, so a voided draft
never burns one. GST wants the series gapless.

Money is collected elsewhere. ``paid_at`` exists so a gateway's webhook can set
it; nothing here does.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from zoneinfo import ZoneInfo
from decimal import ROUND_HALF_UP, Decimal
from typing import Any

from app.config import get_settings
from app.db.pools import service_conn

log = logging.getLogger(__name__)

TWO_PLACES = Decimal("0.01")
DUE_DAYS = 7


def money(value: Decimal | float | int) -> Decimal:
    return Decimal(str(value)).quantize(TWO_PLACES, rounding=ROUND_HALF_UP)


@dataclass(frozen=True, slots=True)
class Tax:
    split: str          # 'cgst_sgst' | 'igst'
    cgst: Decimal
    sgst: Decimal
    igst: Decimal

    @property
    def total(self) -> Decimal:
        return self.cgst + self.sgst + self.igst


def gst(taxable: Decimal, *, rate_percent: Decimal, seller_state: str, buyer_state: str) -> Tax:
    """The split, from the two state codes."""
    total = money(taxable * rate_percent / Decimal(100))
    if seller_state == buyer_state:
        # Two halves that must add back to the total. Half-up rounding of each
        # half can lose a paisa against rounding the total, so the second half
        # is the remainder, not a second rounding.
        cgst = money(total / 2)
        return Tax(split="cgst_sgst", cgst=cgst, sgst=total - cgst, igst=Decimal("0.00"))
    return Tax(split="igst", cgst=Decimal("0.00"), sgst=Decimal("0.00"), igst=total)


DUE_SUBSCRIPTIONS = """
select s.id::text              as subscription_id,
       s.org_id::text          as org_id,
       s.plan_id::text         as plan_id,
       s.coupon_id::text       as coupon_id,
       s.status::text          as status,
       s.current_period_start, s.current_period_end,
       -- The DATE the invoice carries. core.period_date is the one definition
       -- of which day a boundary falls on (IST), shared with the settle walk;
       -- casting the timestamptz here would use the session's UTC and, for a
       -- boundary that is not midnight, a different day from the dedupe below.
       core.period_date(s.current_period_start) as period_start_date,
       core.period_date(s.current_period_end)   as period_end_date,
       p.key                   as plan_key,
       p.name                  as plan_name,
       c.code                  as coupon_code,
       e.list_price_inr, e.percent_off, e.discount_inr, e.price_inr,
       o.legal_name            as buyer_legal_name,
       o.gstin                 as buyer_gstin,
       o.state_code            as buyer_state_code
  from core.subscriptions s
  join core.plans p on p.id = s.plan_id
  join core.organisations o on o.id = s.org_id
  left join core.coupons c on c.id = s.coupon_id
  cross join lateral core.effective_price(s.plan_id, s.coupon_id) e
 where s.product_id = (select id from core.products where key = 'advit')
   and s.cancelled_at is null
   -- Billable states. A trial is not billed; a suspended account is not billed
   -- for the period it was suspended.
   and s.status in ('active', 'pending_payment', 'past_due', 'grace')
   -- A period that has begun on the IST calendar is invoiced; the settle walk
   -- sets boundaries to instants with a time of day, so the comparison is on
   -- the day, not the instant.
   and core.period_date(s.current_period_start) <= %(today)s::date
   and not exists (
         select 1 from core.invoices i
          where i.subscription_id = s.id
            and i.period_start = core.period_date(s.current_period_start)
       )
 order by s.current_period_start, s.id
"""


def raise_invoices(*, today: date | None = None) -> dict[str, Any]:
    settings = get_settings()
    # The IST day: the job runs at 00:30 IST, which is still the previous
    # day in UTC, and a period that began this morning must be invoiced
    # tonight, not tomorrow.
    when = today or datetime.now(ZoneInfo("Asia/Kolkata")).date()
    rate = Decimal(str(settings.gst_rate_percent))
    seller_state = str(settings.seller_state_code or "").strip()

    issued: list[dict[str, Any]] = []
    drafts: list[dict[str, Any]] = []

    if not seller_state or not settings.seller_gstin:
        # Without the seller's own registration nothing can be issued. Every
        # due subscription becomes a draft and the reason is in the job detail,
        # rather than a run that quietly did nothing.
        reason = "SELLER_GSTIN / SELLER_STATE_CODE are not configured; invoices left as drafts"
        log.warning("invoices: %s", reason)

    with service_conn() as conn, conn.cursor() as cur:
        cur.execute(DUE_SUBSCRIPTIONS, {"today": when})
        due = cur.fetchall()

        for row in due:
            list_price = money(row["list_price_inr"])
            discount = money(row["discount_inr"])
            taxable = list_price - discount
            buyer_state = str(row["buyer_state_code"] or "").strip()

            can_issue = bool(seller_state and settings.seller_gstin and buyer_state)
            tax = gst(taxable, rate_percent=rate, seller_state=seller_state,
                      buyer_state=buyer_state) if can_issue else Tax("igst", Decimal(0), Decimal(0), Decimal(0))
            total = taxable + tax.total

            cur.execute(
                """
                insert into core.invoices
                  (org_id, subscription_id, number, status, period_start, period_end,
                   plan_key, plan_name, list_price_inr, coupon_code, percent_off, discount_inr,
                   taxable_inr, gst_rate_percent, sac_code, gst_split,
                   cgst_inr, sgst_inr, igst_inr, total_inr,
                   buyer_legal_name, buyer_gstin, buyer_state_code,
                   seller_gstin, seller_legal_name, issued_at, due_at)
                values
                  (%(org)s::uuid, %(sub)s::uuid,
                   case when %(issue)s then %(prefix)s || '-' || to_char(now(), 'YYYY') || '-'
                                           || lpad(nextval('core.invoice_numbers')::text, 6, '0')
                        else null end,
                   case when %(issue)s then 'issued' else 'draft' end::core.invoice_status,
                   %(period_start)s, %(period_end)s,
                   %(plan_key)s, %(plan_name)s, %(list_price)s, %(coupon_code)s, %(percent_off)s,
                   %(discount)s, %(taxable)s, %(rate)s, %(sac)s, %(split)s,
                   %(cgst)s, %(sgst)s, %(igst)s, %(total)s,
                   %(buyer_name)s, %(buyer_gstin)s, nullif(%(buyer_state)s, ''),
                   nullif(%(seller_gstin)s, ''), nullif(%(seller_name)s, ''),
                   case when %(issue)s then now() end,
                   case when %(issue)s then now() + make_interval(days => %(due_days)s) end)
                returning id::text, number, status::text as status
                """,
                {
                    "org": row["org_id"], "sub": row["subscription_id"], "issue": can_issue,
                    "prefix": settings.invoice_number_prefix,
                    "period_start": row["period_start_date"], "period_end": row["period_end_date"],
                    "plan_key": row["plan_key"], "plan_name": row["plan_name"],
                    "list_price": list_price, "coupon_code": row["coupon_code"],
                    "percent_off": money(row["percent_off"] or 0), "discount": discount,
                    "taxable": taxable, "rate": rate, "sac": settings.gst_sac_code,
                    "split": tax.split, "cgst": tax.cgst, "sgst": tax.sgst, "igst": tax.igst,
                    "total": total,
                    "buyer_name": row["buyer_legal_name"], "buyer_gstin": row["buyer_gstin"],
                    "buyer_state": buyer_state,
                    "seller_gstin": settings.seller_gstin, "seller_name": settings.seller_legal_name,
                    "due_days": DUE_DAYS,
                },
            )
            result = cur.fetchone()
            record = {
                "invoice_id": result["id"], "number": result["number"], "org_id": row["org_id"],
                "plan": row["plan_key"], "total_inr": str(total), "gst_split": tax.split,
            }
            if can_issue:
                issued.append(record)
            else:
                record["reason"] = (
                    "buyer state code missing on the organisation"
                    if seller_state and settings.seller_gstin
                    else "seller GSTIN / state code not configured"
                )
                drafts.append(record)

        if issued or drafts:
            cur.execute(
                """
                select core.log_audit('platform', 'invoices.raised',
                                      p_actor_type => 'automation',
                                      p_payload => jsonb_build_object(
                                        'issued', %s, 'drafts', %s, 'period', %s::text))
                """,
                (len(issued), len(drafts), str(when)),
            )
        conn.commit()

    log.info("invoices: %d issued, %d left as drafts", len(issued), len(drafts))
    return {"considered": len(due), "issued": issued, "drafts": drafts}


_ = timedelta
