-- =============================================================================
-- A metric says where it came from
--
-- The Meta snapshot this repository ships says, in its own `_meta.note`:
--
--     "Metrics are NOT captured here - only structure and health - because
--      metric fixtures go stale silently and invite false confidence."
--
-- That judgement is right and it does not survive contact with an ingestion
-- path, because the fixture driver has to return SOMETHING for a developer to
-- exercise the loop against. The moment it does, t_advit.metrics_daily contains
-- numbers that look exactly like measurement and are not - and everything
-- downstream reads this table: the daily cap, the monthly cap, blended CAC,
-- the contribution margin, the scaling verdict, every report.
--
-- So the fix is not to refuse fixture numbers. It is to make them unable to
-- impersonate real ones. `source` is the column that says which, and
-- `spend_basis_known` below stops being satisfiable by rows this system
-- invented.
--
-- This is the same rule as t_advit.workspaces.spend_basis_known, blended_daily.gaps
-- and the NULL-not-zero work before it: an unknown must not be able to present
-- itself as a measurement. A synthetic row is a third case of that, and the one
-- most likely to be believed, because it arrives through the same code path as
-- the real thing.
-- =============================================================================

do $$ begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
                  where n.nspname = 't_advit' and t.typname = 'metric_source') then
    create type t_advit.metric_source as enum (
      'meta',     -- read from the Meta API. The only kind that is measurement.
      'fixture',  -- generated by FixtureDriver so the loop can be exercised offline.
      'manual'    -- entered by a human, e.g. backfilling a period before onboarding.
    );
  end if;
end $$;

alter table t_advit.metrics_daily
  add column if not exists source t_advit.metric_source;

-- Existing rows are seed data written to stand in for a synced account. Calling
-- them 'meta' would be the exact lie this column exists to prevent, so they are
-- labelled for what they are. The seed now writes this explicitly; this is for
-- a database that already has the rows.
update t_advit.metrics_daily set source = 'fixture' where source is null;

alter table t_advit.metrics_daily
  -- No DEFAULT, deliberately. A default means a writer that forgets the column
  -- gets a provenance it never stated, and the value most likely to be defaulted
  -- to is 'meta' - the one claim that must always be made on purpose.
  alter column source set not null;

comment on column t_advit.metrics_daily.source is
  'Where this row came from. Only ''meta'' is measurement. No default: a writer '
  'that forgets the column must fail rather than silently claim to have read '
  'the number from Meta.';

create index if not exists metrics_daily_source_idx
  on t_advit.metrics_daily (workspace_id, source, date desc);


-- ---------------------------------------------------------------------------
-- What "we have a spend basis" means, now that not every row is one
--
-- t_advit.workspaces.spend_basis_known and month_basis_known are what the tool
-- pipeline consults before comparing a proposed spend against a cap. If a
-- fixture row satisfies them, a developer's offline loop looks - to the
-- guardrail - exactly like a synced production account, and the cap is being
-- checked against numbers this system made up.
-- ---------------------------------------------------------------------------

create or replace function t_advit.has_measured_spend(
  p_workspace uuid,
  p_since     date default null
)
returns boolean
language sql
stable
security definer
set search_path = t_advit, pg_catalog
as $fn$
  select exists (
    select 1
      from t_advit.metrics_daily m
     where m.workspace_id = p_workspace
       and m.source = 'meta'
       and (p_since is null or m.date >= p_since)
  );
$fn$;

revoke execute on function t_advit.has_measured_spend(uuid, date) from public;
grant execute on function t_advit.has_measured_spend(uuid, date)
  to authenticated, advit_backend;

comment on function t_advit.has_measured_spend(uuid, date) is
  'Has this workspace ever had REAL spend ingested? Fixture and manual rows do '
  'not count: a cap compared against a number this system invented is not a cap. '
  'p_since scopes it to a window - the monthly basis asks about this month.';
